(fn ToggleFlight ()
 (bind movement (Variables|Character|GetCharacterMovement))
 (if (Variables|Default|GetFlying)
  (Variables|Default|SetFlying false)
  (Transformation|SetActorLocation :NewLocation (Variables|Default|GetLastWalkPosition) :bTeleport true)
  (Pawn|Components|CharacterMovement|SetMovementMode :self movement :NewMovementMode "MOVE_Walking")
  (else
   (Variables|Default|SetLastWalkPosition (Transformation|GetActorLocation))
   (Variables|Default|SetFlying true)
   (Pawn|Components|CharacterMovement|SetMovementMode :self movement :NewMovementMode "MOVE_Flying"))))
(fn ReturnToGate ()
 (Variables|Default|SetFlying false)
 (Transformation|SetActorLocation :NewLocation (Math|Vector|MakeVector -1450 3000 120) :bTeleport true)
 (Pawn|Components|CharacterMovement|SetMovementMode :self (Variables|Character|GetCharacterMovement) :NewMovementMode "MOVE_Walking"))
(event EventBeginPlay
 (Input|SetInputModeGameOnly (Game|GetPlayerController 0)))
(event EventTick (DeltaSeconds)
 (bind pc (Game|GetPlayerController 0))
 (bind movement (Variables|Character|GetCharacterMovement))
 (bind (mx my) (Game|Player|GetInputMouseDelta :self pc))
 (Pawn|Input|AddControllerYawInput :Val (* mx 0.7))
 (Pawn|Input|AddControllerPitchInput :Val (* my -0.7))
 (bind forward (- (select (Game|Player|IsInputKeyDown :self pc :Key "W") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "S") 1.0 0.0)))
 (bind right (- (select (Game|Player|IsInputKeyDown :self pc :Key "D") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "A") 1.0 0.0)))
 (bind fast (Game|Player|IsInputKeyDown :self pc :Key "LeftShift"))
 (Class|CharacterMovementComponent|SetMaxWalkSpeed :self movement :MaxWalkSpeed (select fast 750.0 420.0))
 (Class|CharacterMovementComponent|SetMaxFlySpeed :self movement :MaxFlySpeed (select fast 5000.0 1800.0))
 (if (Variables|Default|GetFlying)
  (Pawn|Input|AddMovementInput :WorldDirection (Math|Vector|GetForwardVector (Pawn|GetControlRotation :self pc)) :ScaleValue forward)
  (Pawn|Input|AddMovementInput :WorldDirection (Math|Vector|MakeVector 0 0 1) :ScaleValue (- (select (Game|Player|IsInputKeyDown :self pc :Key "E") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "Q") 1.0 0.0)))
  (else (Pawn|Input|AddMovementInput :WorldDirection (Transformation|GetActorForwardVector) :ScaleValue forward)))
 (Pawn|Input|AddMovementInput :WorldDirection (Transformation|GetActorRightVector) :ScaleValue right)
 (if (Game|Player|WasInputKeyJustPressed :self pc :Key "Tab") (CallFunction|ToggleFlight))
 (if (Game|Player|WasInputKeyJustPressed :self pc :Key "SpaceBar") (Character|Jump))
 (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "R") (< (.z (Transformation|GetActorLocation)) -500.0)) (CallFunction|ReturntoGate)))