(fn SaveTourProgress ()
(bind object (SaveGame|CreateSaveGameObject :SaveGameClass "/Game/WZMS/Blueprints/BP_WZMS_TourSave.BP_WZMS_TourSave_C"))
 (bind saved (Utilities|Casting|CastToBP_WZMS_TourSave :Object object)
  (:then (Class|BPWZMSTourSave|SetSavedPosition :self saved :SavedPosition (Variables|Default|GetSafePosition))
(Class|BPWZMSTourSave|SetSavedRotation :self saved :SavedRotation (Variables|Default|GetSafeRotation))
(Class|BPWZMSTourSave|SetSavedQuality :self saved :SavedQuality (Variables|Default|GetQualityPreset))
(Class|BPWZMSTourSave|SetSavedVolume :self saved :SavedVolume (Variables|Default|GetTourVolume))
(Class|BPWZMSTourSave|SetSavedVersion :self saved :SavedVersion 1)
   (bind success (SaveGame|SaveGametoSlot :SaveGameObject saved :SlotName "WZMS_CampusTour" :UserIndex 0))
   (Variables|Default|SetSaveSucceeded success)
   (if success (Variables|Default|SetHasSavedVisit true)))
  (:CastFailed (Variables|Default|SetSaveSucceeded false)))
)

(fn RestoreTourSafePosition ()
(Variables|Default|SetFlying false)
 (Pawn|Components|CharacterMovement|SetMovementMode :self (Variables|Character|GetCharacterMovement) :NewMovementMode "MOVE_Walking")
 (Transformation|SetActorLocation :NewLocation (Variables|Default|GetSafePosition) :bTeleport true)
 (Pawn|SetControlRotation :self (Game|GetPlayerController 0) :NewRotation (Variables|Default|GetSafeRotation))
 (Variables|Default|SetLastWalkPosition (Variables|Default|GetSafePosition))
)

(fn ApplyTourQuality (Quality)
(Variables|Default|SetQualityPreset Quality)
 (bind settings (Settings|GetGameUserSettings))
   (Settings|SetOverallScalabilityLevel :self settings :Value Quality)
   (Settings|SetResolutionScaleValue :self settings :NewScaleValue 100)
 (Settings|ApplySettings :self settings :bCheckForCommandLineOverrides false)
 (Settings|SaveSettings :self settings)
)

(fn ApplyTourSoundLevel (Volume)
(Variables|Default|SetTourVolume Volume)
(Audio|SetSoundMixClassOverride :InSoundMixModifier "/Game/WZMS/Tour/Audio/Mix_Tour.Mix_Tour" :InSoundClass "/Game/WZMS/Tour/Audio/SC_Tour.SC_Tour" :Volume Volume :Pitch 1 :FadeInTime 0.25 :bApplyToChildren true)
)

(fn SetTourMenuState (Open)
(Variables|Default|SetTourMenuOpen Open)
 (if Open (Components|Movement|StopMovementImmediately :self (Variables|Character|GetCharacterMovement)))
)

(fn GetTourQuality ()
(return (Variables|Default|GetQualityPreset))
)

(fn ReadTourSoundLevel ()
(return (Variables|Default|GetTourVolume))
)

(fn GetTourSaveSucceeded ()
(return (Variables|Default|GetSaveSucceeded))
)

(fn GetHasSavedVisit ()
(return (Variables|Default|GetHasSavedVisit))
)

(fn InitializeTour ()
(Audio|PushSoundMixModifier :InSoundMixModifier "/Game/WZMS/Tour/Audio/Mix_Tour.Mix_Tour")
 (bind object (SaveGame|LoadGamefromSlot :SlotName "WZMS_CampusTour" :UserIndex 0))
 (bind saved (Utilities|Casting|CastToBP_WZMS_TourSave :Object object)
  (:then
   (if (and (== (Class|BPWZMSTourSave|GetSavedVersion :self saved) 1) (and (> (.z (Class|BPWZMSTourSave|GetSavedPosition :self saved)) -20) (< (.z (Class|BPWZMSTourSave|GetSavedPosition :self saved)) 2000)))
    (Variables|Default|SetSafePosition (Class|BPWZMSTourSave|GetSavedPosition :self saved)) (Variables|Default|SetSafeRotation (Class|BPWZMSTourSave|GetSavedRotation :self saved))
    (Variables|Default|SetQualityPreset (Class|BPWZMSTourSave|GetSavedQuality :self saved)) (Variables|Default|SetTourVolume (Class|BPWZMSTourSave|GetSavedVolume :self saved)) (Variables|Default|SetHasSavedVisit true))
   (CallFunction|ApplyTourQuality :Quality (Variables|Default|GetQualityPreset)) (CallFunction|ApplyTourSoundLevel :Volume (Variables|Default|GetTourVolume)) (CallFunction|RestoreTourSafePosition))
  (:CastFailed (CallFunction|ApplyTourQuality :Quality (Variables|Default|GetQualityPreset)) (CallFunction|ApplyTourSoundLevel :Volume (Variables|Default|GetTourVolume)) (CallFunction|RestoreTourSafePosition)))
)

(fn TravelToTourPlace (Index)
(switch int Index
(:0 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -1450.0 3000.0 92.9999885559082)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:1 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -866.7000732421875 -2166.7000045776367 92.99996566772461)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:2 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 5100.0 1500.0 92.99996948242188)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:3 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 10000.0 -1500.0000381469727 92.9999885559082)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 180)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:4 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 1800.0 -4700.0 92.9999885559082)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:5 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -8100.0 -13600.0 94.00000381469727)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:6 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -2900.000015258789 -10599.999816894531 94.00000762939453)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:7 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -2699.9999389648438 -13050.0 94.00000381469727)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 180)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:8 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -4200.000183105469 -16200.0 94.59999465942383)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:9 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 300.00001525878906 -16400.0 97.0000228881836)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:10 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -2000.0001525878906 -21800.0 97.00003051757812)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:11 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -11999.999938964844 -16900.0 94.00000381469727)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:12 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -4423.000183105469 -32219.0 97.00001907348633)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:13 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 7.62939453125e-05 -25899.999389648438 96.49995803833008)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:14 (Variables|Default|SetSafePosition (Math|Vector|MakeVector -7600.000061035156 -39200.0 202.89998626708984)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:15 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 5400.000045776367 -36700.0 93.20001220703125)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:16 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 12440.000396728516 -35130.0 200.00002670288086)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw -90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:17 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 14300.0 -29399.999633789062 94.00001907348633)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:18 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 11600.000061035156 -15500.0 94.80000114440918)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:19 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 14700.000061035156 -12099.999938964844 94.89999198913574)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:20 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 24700.000061035156 -12000.000366210938 93.99995803833008)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:21 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 21099.999908447266 -8200.000091552734 96.40004348754883)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 90)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:22 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 28200.000244140625 -11200.0 93.99998092651367)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress))
(:23 (Variables|Default|SetSafePosition (Math|Vector|MakeVector 34600.0 -11500.0 93.9999885559082)) (Variables|Default|SetSafeRotation (Math|Rotator|MakeRotator :Roll 0 :Pitch 0 :Yaw 0)) (CallFunction|RestoreTourSafePosition) (CallFunction|SaveTourProgress)))
)

(event EventBeginPlay (CallFunction|InitializeTour))
(event EventEndPlay (EndPlayReason) (CallFunction|SaveTourProgress))
(event EventTick (DeltaSeconds)
 (if (not (Variables|Default|GetTourMenuOpen))
  (bind pc (Game|GetPlayerController 0))
  (bind movement (Variables|Character|GetCharacterMovement))
  (bind (mx my) (Game|Player|GetInputMouseDelta :self pc))
  (Pawn|Input|AddControllerYawInput :Val (* mx 0.7))
  (Pawn|Input|AddControllerPitchInput :Val (* my -0.7))
  (bind forward (- (select (Game|Player|IsInputKeyDown :self pc :Key "W") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "S") 1.0 0.0)))
  (bind right (- (select (Game|Player|IsInputKeyDown :self pc :Key "D") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "A") 1.0 0.0)))
  (bind fast (Game|Player|IsInputKeyDown :self pc :Key "LeftShift"))
  (Class|CharacterMovementComponent|SetMaxWalkSpeed :self movement :MaxWalkSpeed (select fast 750.0 420.0))
  (Class|CharacterMovementComponent|SetMaxFlySpeed :self movement :MaxFlySpeed (select fast 5000.0 1800.0))
  (if (Variables|Default|GetFlying)
   (Pawn|Input|AddMovementInput :WorldDirection (Math|Vector|GetForwardVector (Pawn|GetControlRotation :self pc)) :ScaleValue forward)
   (Pawn|Input|AddMovementInput :WorldDirection (Math|Vector|MakeVector 0 0 1) :ScaleValue (- (select (Game|Player|IsInputKeyDown :self pc :Key "E") 1.0 0.0) (select (Game|Player|IsInputKeyDown :self pc :Key "Q") 1.0 0.0)))
   (else (Pawn|Input|AddMovementInput :WorldDirection (Transformation|GetActorForwardVector) :ScaleValue forward)))
  (Pawn|Input|AddMovementInput :WorldDirection (Transformation|GetActorRightVector) :ScaleValue right)
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "Tab") (CallFunction|ToggleFlight))
  (if (Game|Player|WasInputKeyJustPressed :self pc :Key "SpaceBar") (Character|Jump))
  (if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "R") (< (.z (Transformation|GetActorLocation)) -500.0)) (CallFunction|RestoreTourSafePosition))
  (if (and (not (Variables|Default|GetFlying)) (Movement|IsMovingonGround :self movement))
   (Variables|Default|SetSafePosition (Transformation|GetActorLocation))
   (Variables|Default|SetSafeRotation (Pawn|GetControlRotation :self pc)))
  (Variables|Default|SetTourSaveClock (+ (Variables|Default|GetTourSaveClock) DeltaSeconds))
  (if (> (Variables|Default|GetTourSaveClock) 10) (Variables|Default|SetTourSaveClock 0) (CallFunction|SaveTourProgress))))