(fn DrawTourLabel (Label X Y Size TextColor)
(HUD|DrawText :Text Label :TextColor TextColor :ScreenX X :ScreenY Y :Font "/Game/WZMS/Tour/UI/F_Tour_Chinese_Font.F_Tour_Chinese_Font" :Scale (* (/ Size 64.0) (Variables|Default|GetUIScale)))
)

(fn DrawTourButton (ButtonName Label X Y W H Selected)
(HUD|DrawRect :RectColor (select (or (== (Variables|Default|GetHoverName) ButtonName) Selected) (Utilities|Struct|MakeLinearColor :R 0.12 :G 0.28 :B 0.23 :A 0.98) (Utilities|Struct|MakeLinearColor :R 0.065 :G 0.13 :B 0.11 :A 0.98)) :ScreenX (+ (Variables|Default|GetUIOriginX) (* X (Variables|Default|GetUIScale))) :ScreenY (+ (Variables|Default|GetUIOriginY) (* Y (Variables|Default|GetUIScale))) :ScreenW (* W (Variables|Default|GetUIScale)) :ScreenH (* H (Variables|Default|GetUIScale)))
(CallFunction|DrawTourLabel :Label Label :X (+ (Variables|Default|GetUIOriginX) (* (+ X 10) (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* (+ Y 5) (Variables|Default|GetUIScale))) :Size 16 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(HUD|AddHitBox :Position (Math|Vector2D|MakeVector2D (+ (Variables|Default|GetUIOriginX) (* X (Variables|Default|GetUIScale))) (+ (Variables|Default|GetUIOriginY) (* Y (Variables|Default|GetUIScale)))) :Size (Math|Vector2D|MakeVector2D (* W (Variables|Default|GetUIScale)) (* H (Variables|Default|GetUIScale))) :InName ButtonName :bConsumesInput true :Priority 1)
)

(fn DrawTourMapDot (X Y Side U V Span DotU DotV Label ClickName Labels Major)
(bind dx (/ (- DotU U) Span)) (bind dy (/ (- DotV V) Span))
 (if (and (and (> dx 0.02) (< dx 0.98)) (and (> dy 0.02) (< dy 0.98)))
  (bind px (+ X (* dx Side))) (bind py (+ Y (* dy Side)))
  (HUD|DrawRect :RectColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1) :ScreenX (- px 3) :ScreenY (- py 3) :ScreenW 6 :ScreenH 6)
  (if (and Labels Major) (CallFunction|DrawTourLabel :Label Label :X (+ px 5) :Y (- py 6) :Size 11 :TextColor (Utilities|Struct|MakeLinearColor :R 1 :G 1 :B 1 :A 1)))
  (if Labels (HUD|AddHitBox :Position (Math|Vector2D|MakeVector2D (- px 7) (- py 7)) :Size (Math|Vector2D|MakeVector2D 14 14) :InName ClickName :bConsumesInput true :Priority 1)))
)

(fn ConsiderTourPlace (X Y Label)
(bind dx (- (Variables|Default|GetPlayerX) X)) (bind dy (- (Variables|Default|GetPlayerY) Y))
 (bind distance (+ (* dx dx) (* dy dy)))
 (if (< distance (Variables|Default|GetNearestDistance)) (Variables|Default|SetNearestDistance distance) (Variables|Default|SetNearestPlace Label))
)

(fn SetTourMenu (Open)
(Variables|Default|SetMenuOpen Open) (Variables|Default|SetHelpOpen false)
 (bind pc (Game|GetPlayerController 0))
 (Class|PlayerController|SetShowMouseCursor :self pc :bShowMouseCursor Open)
 (Class|PlayerController|SetEnableClickEvents :self pc :bEnableClickEvents Open)
 (Class|PlayerController|SetEnableMouseOverEvents :self pc :bEnableMouseOverEvents Open)
 (if Open
  (Input|SetInputModeGameAndUI :PlayerController pc :InMouseLockMode "DoNotLock" :bHideCursorDuringCapture false)
  (else (Input|SetInputModeGameOnly :PlayerController pc)))
 (Game|SetGamePaused :bPaused Open)
 (bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
  (:then (Class|BPWZMSExplorer|SetTourMenuState :self explorer :Open Open) (Class|BPWZMSExplorer|SaveTourProgress :self explorer)) (:CastFailed))
)

(fn ToggleTourMenu ()
(CallFunction|SetTourMenu :Open (not (Variables|Default|GetMenuOpen)))
)

(fn VisitTourPlace (Index)
(bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
 (:then (Class|BPWZMSExplorer|TraveltoTourPlace :self explorer :Index Index) (CallFunction|SetTourMenu :Open false)) (:CastFailed))
)

(fn SelectTourQuality (Quality)
(Variables|Default|SetHUDQuality Quality)
 (bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
 (:then (Class|BPWZMSExplorer|ApplyTourQuality :self explorer :Quality Quality) (Class|BPWZMSExplorer|SaveTourProgress :self explorer)) (:CastFailed))
)

(fn CycleTourVolume ()
(Variables|Default|SetHUDVolume (select (< (Variables|Default|GetHUDVolume) 0.1) 0.35 (select (< (Variables|Default|GetHUDVolume) 0.5) 0.65 (select (< (Variables|Default|GetHUDVolume) 0.9) 1.0 0.0))))
 (bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
 (:then (Class|BPWZMSExplorer|ApplyTourSoundLevel :self explorer :Volume (Variables|Default|GetHUDVolume)) (Class|BPWZMSExplorer|SaveTourProgress :self explorer)) (:CastFailed))
)

(fn InitializeTourHUD ()
(bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
 (:then (Class|BPWZMSExplorer|RestoreTourSafePosition :self explorer) (Variables|Default|SetHUDQuality (Class|BPWZMSExplorer|GetTourQuality :self explorer)) (Variables|Default|SetHUDVolume (Class|BPWZMSExplorer|ReadTourSoundLevel :self explorer)) (Variables|Default|SetInitialized true) (CallFunction|SetTourMenu :Open true)) (:CastFailed))
)

(fn DrawTourMap (X Y Side U V Span Labels)
(HUD|DrawTexture :Texture "/Game/WZMS/Tour/UI/T_Tour_CampusMap.T_Tour_CampusMap" :ScreenX X :ScreenY Y :ScreenW Side :ScreenH Side :TextureU U :TextureV V :TextureUWidth Span :TextureVHeight Span :BlendMode "BLEND_Opaque")
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.2991935483870968 :DotV 0.8467741935483871 :Label "南大门" :ClickName "POI00" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.3086016117219002 :DotV 0.7634403225068123 :Label "南大门广场" :ClickName "POI01" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.40483870967741936 :DotV 0.8225806451612904 :Label "网球场" :ClickName "POI02" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.4838709677419355 :DotV 0.774193547771823 :Label "荷屿" :ClickName "POI03" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.35161290322580646 :DotV 0.7225806451612903 :Label "德涵楼·贯真楼" :ClickName "POI04" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.19193548387096773 :DotV 0.5790322580645161 :Label "道司前路" :ClickName "POI05" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.2758064513667937 :DotV 0.6274193577920237 :Label "榕屿" :ClickName "POI06" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.2790322590489541 :DotV 0.5879032258064516 :Label "籀园学堂" :ClickName "POI07" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.2548387067241053 :DotV 0.5370967741935484 :Label "校友风采" :ClickName "POI08" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.3274193550848192 :DotV 0.5338709677419354 :Label "步青广场" :ClickName "POI09" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.2903225781840663 :DotV 0.4467741935483871 :Label "南田路" :ClickName "POI10" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.12903225904895413 :DotV 0.5258064516129032 :Label "西门" :ClickName "POI11" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.25124193253055693 :DotV 0.27872580645161293 :Label "操场" :ClickName "POI12" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.32258064639183787 :DotV 0.3806451711347026 :Label "篮球场" :ClickName "POI13" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.199999999015562 :DotV 0.16612903225806452 :Label "体育馆" :ClickName "POI14" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.4096774200931672 :DotV 0.2064516129032258 :Label "北门" :ClickName "POI15" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.5232258128504599 :DotV 0.23177419354838708 :Label "食堂" :ClickName "POI16" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.5532258064516129 :DotV 0.32419355429372476 :Label "竹屿" :ClickName "POI17" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.5096774203392767 :DotV 0.5483870967741935 :Label "图书馆" :ClickName "POI18" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.5596774203392767 :DotV 0.6032258074360509 :Label "数学馆" :ClickName "POI19" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.7209677429199218 :DotV 0.6048387037707913 :Label "校史馆" :ClickName "POI20" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.6629032243297945 :DotV 0.6661290307814075 :Label "桃花岛" :ClickName "POI21" :Labels Labels :Major true)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.7774193587764617 :DotV 0.617741935483871 :Label "梅花岛" :ClickName "POI22" :Labels Labels :Major false)
(CallFunction|DrawTourMapDot :X X :Y Y :Side Side :U U :V V :Span Span :DotU 0.8806451612903226 :DotV 0.6129032258064516 :Label "橘岛" :ClickName "POI23" :Labels Labels :Major false)
(bind pawn (Game|GetPlayerPawn 0))
(bind pos (Transformation|GetActorLocation :self pawn))
(bind direction (Transformation|GetActorForwardVector :self pawn))
(bind px (+ X (* (/ (- (/ (+ (.x pos) 20000) 62000) U) Span) Side)))
(bind py (+ Y (* (/ (- (/ (+ (.y pos) 49500) 62000) V) Span) Side)))
(HUD|DrawLine :StartScreenX (+ px (* (.x direction) 10)) :StartScreenY (+ py (* (.y direction) 10)) :EndScreenX (- (- px (* (.x direction) 7)) (* (.y direction) 6)) :EndScreenY (+ (- py (* (.y direction) 7)) (* (.x direction) 6)) :LineColor (Utilities|Struct|MakeLinearColor :R 1 :G 0.65 :B 0.26 :A 1) :LineThickness 2.5)
(HUD|DrawLine :StartScreenX (+ px (* (.x direction) 10)) :StartScreenY (+ py (* (.y direction) 10)) :EndScreenX (+ (- px (* (.x direction) 7)) (* (.y direction) 6)) :EndScreenY (- (- py (* (.y direction) 7)) (* (.x direction) 6)) :LineColor (Utilities|Struct|MakeLinearColor :R 1 :G 0.65 :B 0.26 :A 1) :LineThickness 2.5)
(HUD|DrawLine :StartScreenX (- (- px (* (.x direction) 7)) (* (.y direction) 6)) :StartScreenY (+ (- py (* (.y direction) 7)) (* (.x direction) 6)) :EndScreenX (+ (- px (* (.x direction) 7)) (* (.y direction) 6)) :EndScreenY (- (- py (* (.y direction) 7)) (* (.x direction) 6)) :LineColor (Utilities|Struct|MakeLinearColor :R 1 :G 0.65 :B 0.26 :A 1) :LineThickness 2.5)
)

(fn DrawTourMenu ()
(HUD|DrawRect :RectColor (Utilities|Struct|MakeLinearColor :R 0 :G 0 :B 0 :A 0.55) :ScreenX 0 :ScreenY 0 :ScreenW (Variables|Default|GetUIWidth) :ScreenH (Variables|Default|GetUIHeight))
(HUD|DrawRect :RectColor (Utilities|Struct|MakeLinearColor :R 0.035 :G 0.075 :B 0.065 :A 0.97) :ScreenX (+ (Variables|Default|GetUIOriginX) (* 36 (Variables|Default|GetUIScale))) :ScreenY (+ (Variables|Default|GetUIOriginY) (* 48 (Variables|Default|GetUIScale))) :ScreenW (* 1208 (Variables|Default|GetUIScale)) :ScreenH (* 628 (Variables|Default|GetUIScale)))
(CallFunction|DrawTourLabel :Label "温州中学" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 70 (Variables|Default|GetUIScale))) :Size 30 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "校园漫游" :X (+ (Variables|Default|GetUIOriginX) (* 222 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 80 (Variables|Default|GetUIScale))) :Size 16 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "选择一个地点，开始自由游览" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 114 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(if (Variables|Default|GetHelpOpen) (CallFunction|DrawTourLabel :Label "操作说明" :X (+ (Variables|Default|GetUIOriginX) (* 704 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 110 (Variables|Default|GetUIScale))) :Size 24 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "自由游览" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 168 (Variables|Default|GetUIScale))) :Size 22 :TextColor (Utilities|Struct|MakeLinearColor :R 0.39 :G 0.77 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "W / A / S / D" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 216 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "前后左右移动" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 239 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "鼠标" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 278 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "环顾四周" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 301 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "Shift" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 340 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "加快行走" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 363 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "空格" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 402 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "跳跃" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 425 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "M / Esc" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 464 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "打开或关闭校园地图" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 487 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "观赏与安全" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 168 (Variables|Default|GetUIScale))) :Size 22 :TextColor (Utilities|Struct|MakeLinearColor :R 0.39 :G 0.77 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "Tab" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 216 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "切换航拍；再次按下回到起飞处" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 239 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "Q / E" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 278 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "航拍时下降 / 上升" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 301 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "R" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 340 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "回到最近安全位置" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 363 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "自动存档" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 402 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "行走时定期保存，也会在离开菜单时保存" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 425 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "水域" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 464 (Variables|Default|GetUIScale))) :Size 17 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "仅作为环境；请通过桥梁游览各岛屿" :X (+ (Variables|Default|GetUIOriginX) (* 644 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 487 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1)) (else (CallFunction|DrawTourButton :ButtonName "POI00" :Label "01  南大门" :X 64 :Y 148 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI01" :Label "02  南大门广场" :X 64 :Y 181 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI02" :Label "03  网球场" :X 64 :Y 214 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI03" :Label "04  荷屿" :X 64 :Y 247 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI04" :Label "05  德涵楼·贯真楼" :X 64 :Y 280 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI05" :Label "06  道司前路" :X 64 :Y 313 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI06" :Label "07  榕屿" :X 64 :Y 346 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI07" :Label "08  籀园学堂" :X 64 :Y 379 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI08" :Label "09  校友风采" :X 64 :Y 412 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI09" :Label "10  步青广场" :X 64 :Y 445 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI10" :Label "11  南田路" :X 64 :Y 478 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI11" :Label "12  西门" :X 64 :Y 511 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI12" :Label "13  操场" :X 368 :Y 148 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI13" :Label "14  篮球场" :X 368 :Y 181 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI14" :Label "15  体育馆" :X 368 :Y 214 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI15" :Label "16  北门" :X 368 :Y 247 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI16" :Label "17  食堂" :X 368 :Y 280 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI17" :Label "18  竹屿" :X 368 :Y 313 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI18" :Label "19  图书馆" :X 368 :Y 346 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI19" :Label "20  数学馆" :X 368 :Y 379 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI20" :Label "21  校史馆" :X 368 :Y 412 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI21" :Label "22  桃花岛" :X 368 :Y 445 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI22" :Label "23  梅花岛" :X 368 :Y 478 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourButton :ButtonName "POI23" :Label "24  橘岛" :X 368 :Y 511 :W 288 :H 28 :Selected false)
(CallFunction|DrawTourMap :X (+ (Variables|Default|GetUIOriginX) (* 704 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 136 (Variables|Default|GetUIScale))) :Side (* 488 (Variables|Default|GetUIScale)) :U 0 :V 0 :Span 1 :Labels true)
(CallFunction|DrawTourLabel :Label "北 ↑" :X (+ (Variables|Default|GetUIOriginX) (* 1150 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 108 (Variables|Default|GetUIScale))) :Size 16 :TextColor (Utilities|Struct|MakeLinearColor :R 0.39 :G 0.77 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "点击地图上的地点也可直接到达" :X (+ (Variables|Default|GetUIOriginX) (* 704 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 632 (Variables|Default|GetUIScale))) :Size 14 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))))
(CallFunction|DrawTourLabel :Label "画质" :X (+ (Variables|Default|GetUIOriginX) (* 64 (Variables|Default|GetUIScale))) :Y (+ (Variables|Default|GetUIOriginY) (* 558 (Variables|Default|GetUIScale))) :Size 15 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourButton :ButtonName "Quality1" :Label "流畅" :X 114 :Y 552 :W 96 :H 30 :Selected (== (Variables|Default|GetHUDQuality) 1))
(CallFunction|DrawTourButton :ButtonName "Quality2" :Label "均衡" :X 218 :Y 552 :W 96 :H 30 :Selected (== (Variables|Default|GetHUDQuality) 2))
(CallFunction|DrawTourButton :ButtonName "Quality3" :Label "精致" :X 322 :Y 552 :W 96 :H 30 :Selected (== (Variables|Default|GetHUDQuality) 3))
(CallFunction|DrawTourButton :ButtonName "Volume" :Label (select (< (Variables|Default|GetHUDVolume) 0.1) "声音：关闭" (select (< (Variables|Default|GetHUDVolume) 0.5) "声音：轻柔" (select (< (Variables|Default|GetHUDVolume) 0.9) "声音：适中" "声音：完整"))) :X 432 :Y 552 :W 160 :H 30 :Selected false)
(CallFunction|DrawTourButton :ButtonName "Continue" :Label "继续游览" :X 64 :Y 614 :W 176 :H 38 :Selected false)
(CallFunction|DrawTourButton :ButtonName "Help" :Label (select (Variables|Default|GetHelpOpen) "返回地图" "操作说明") :X 256 :Y 614 :W 176 :H 38 :Selected false)
(CallFunction|DrawTourButton :ButtonName "Exit" :Label "保存并退出" :X 448 :Y 614 :W 176 :H 38 :Selected false)
)

(fn DrawTourMinimap ()
(bind pawn (Game|GetPlayerPawn 0))
(bind pos (Transformation|GetActorLocation :self pawn))
(bind x (- (Variables|Default|GetUIWidth) (* 276 (Variables|Default|GetUIScale))))
(bind y (* 24 (Variables|Default|GetUIScale)))
(bind rawu (- (/ (+ (.x pos) 20000) 62000) 0.14516129))
(bind rawv (- (/ (+ (.y pos) 49500) 62000) 0.14516129))
(bind u (select (< rawu 0.0) 0.0 (select (> rawu 0.70967742) 0.70967742 rawu)))
(bind v (select (< rawv 0.0) 0.0 (select (> rawv 0.70967742) 0.70967742 rawv)))
(HUD|DrawRect :RectColor (Utilities|Struct|MakeLinearColor :R 0.035 :G 0.075 :B 0.065 :A 0.97) :ScreenX x :ScreenY y :ScreenW (* 252 (Variables|Default|GetUIScale)) :ScreenH (* 292 (Variables|Default|GetUIScale)))
(CallFunction|DrawTourMap :X (+ x (* 6 (Variables|Default|GetUIScale))) :Y (+ y (* 6 (Variables|Default|GetUIScale))) :Side (* 240 (Variables|Default|GetUIScale)) :U u :V v :Span 0.29032258 :Labels false)
(CallFunction|DrawTourLabel :Label (Variables|Default|GetNearestPlace) :X (+ x (* 10 (Variables|Default|GetUIScale))) :Y (+ y (* 250 (Variables|Default|GetUIScale))) :Size 16 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(CallFunction|DrawTourLabel :Label "M 地图" :X (+ x (* 174 (Variables|Default|GetUIScale))) :Y (+ y (* 250 (Variables|Default|GetUIScale))) :Size 14 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
(CallFunction|DrawTourLabel :Label "北 ↑" :X (+ x (* 208 (Variables|Default|GetUIScale))) :Y (+ y (* 10 (Variables|Default|GetUIScale))) :Size 13 :TextColor (Utilities|Struct|MakeLinearColor :R 0.94 :G 0.96 :B 0.93 :A 1))
(HUD|DrawRect :RectColor (Utilities|Struct|MakeLinearColor :R 1 :G 1 :B 1 :A 0.55) :ScreenX (- (/ (Variables|Default|GetUIWidth) 2) 1) :ScreenY (- (/ (Variables|Default|GetUIHeight) 2) 1) :ScreenW 2 :ScreenH 2)
(CallFunction|DrawTourLabel :Label "WASD 行走   ·   Tab 航拍   ·   M 校园地图" :X (* 24 (Variables|Default|GetUIScale)) :Y (- (Variables|Default|GetUIHeight) (* 32 (Variables|Default|GetUIScale))) :Size 14 :TextColor (Utilities|Struct|MakeLinearColor :R 0.55 :G 0.66 :B 0.62 :A 1))
)

(event EventReceiveDrawHUD (SizeX SizeY)
(Variables|Default|SetUIWidth SizeX)
(Variables|Default|SetUIHeight SizeY)
(Variables|Default|SetUIScale (select (< (/ SizeX 1280.0) (/ SizeY 720.0)) (/ SizeX 1280.0) (/ SizeY 720.0)))
(Variables|Default|SetUIOriginX (/ (- SizeX (* 1280 (Variables|Default|GetUIScale))) 2))
(Variables|Default|SetUIOriginY (/ (- SizeY (* 720 (Variables|Default|GetUIScale))) 2))
(if (not (Variables|Default|GetInitialized)) (CallFunction|InitializeTourHUD))
(bind pc (Game|GetPlayerController 0))
(if (or (Game|Player|WasInputKeyJustPressed :self pc :Key "M") (Game|Player|WasInputKeyJustPressed :self pc :Key "Escape")) (CallFunction|ToggleTourMenu))
(bind pos (Transformation|GetActorLocation :self (Game|GetPlayerPawn 0)))
(Variables|Default|SetNearestDistance 100000000000)
(Variables|Default|SetPlayerX (.x pos))
(Variables|Default|SetPlayerY (.y pos))
(CallFunction|ConsiderTourPlace :X -1450.0 :Y 3000.0 :Label "南大门")
(CallFunction|ConsiderTourPlace :X -866.7000732421875 :Y -2166.7000045776367 :Label "南大门广场")
(CallFunction|ConsiderTourPlace :X 5100.0 :Y 1500.0 :Label "网球场")
(CallFunction|ConsiderTourPlace :X 10000.0 :Y -1500.0000381469727 :Label "荷屿")
(CallFunction|ConsiderTourPlace :X 1800.0 :Y -4700.0 :Label "德涵楼·贯真楼")
(CallFunction|ConsiderTourPlace :X -8100.0 :Y -13600.0 :Label "道司前路")
(CallFunction|ConsiderTourPlace :X -2900.000015258789 :Y -10599.999816894531 :Label "榕屿")
(CallFunction|ConsiderTourPlace :X -2699.9999389648438 :Y -13050.0 :Label "籀园学堂")
(CallFunction|ConsiderTourPlace :X -4200.000183105469 :Y -16200.0 :Label "校友风采")
(CallFunction|ConsiderTourPlace :X 300.00001525878906 :Y -16400.0 :Label "步青广场")
(CallFunction|ConsiderTourPlace :X -2000.0001525878906 :Y -21800.0 :Label "南田路")
(CallFunction|ConsiderTourPlace :X -11999.999938964844 :Y -16900.0 :Label "西门")
(CallFunction|ConsiderTourPlace :X -4423.000183105469 :Y -32219.0 :Label "操场")
(CallFunction|ConsiderTourPlace :X 7.62939453125e-05 :Y -25899.999389648438 :Label "篮球场")
(CallFunction|ConsiderTourPlace :X -7600.000061035156 :Y -39200.0 :Label "体育馆")
(CallFunction|ConsiderTourPlace :X 5400.000045776367 :Y -36700.0 :Label "北门")
(CallFunction|ConsiderTourPlace :X 12440.000396728516 :Y -35130.0 :Label "食堂")
(CallFunction|ConsiderTourPlace :X 14300.0 :Y -29399.999633789062 :Label "竹屿")
(CallFunction|ConsiderTourPlace :X 11600.000061035156 :Y -15500.0 :Label "图书馆")
(CallFunction|ConsiderTourPlace :X 14700.000061035156 :Y -12099.999938964844 :Label "数学馆")
(CallFunction|ConsiderTourPlace :X 24700.000061035156 :Y -12000.000366210938 :Label "校史馆")
(CallFunction|ConsiderTourPlace :X 21099.999908447266 :Y -8200.000091552734 :Label "桃花岛")
(CallFunction|ConsiderTourPlace :X 28200.000244140625 :Y -11200.0 :Label "梅花岛")
(CallFunction|ConsiderTourPlace :X 34600.0 :Y -11500.0 :Label "橘岛")
(if (Variables|Default|GetMenuOpen) (CallFunction|DrawTourMenu) (else (CallFunction|DrawTourMinimap))))
(event EventHitBoxClicked (BoxName)
(if (== BoxName "POI00") (CallFunction|VisitTourPlace :Index 0))
(if (== BoxName "POI01") (CallFunction|VisitTourPlace :Index 1))
(if (== BoxName "POI02") (CallFunction|VisitTourPlace :Index 2))
(if (== BoxName "POI03") (CallFunction|VisitTourPlace :Index 3))
(if (== BoxName "POI04") (CallFunction|VisitTourPlace :Index 4))
(if (== BoxName "POI05") (CallFunction|VisitTourPlace :Index 5))
(if (== BoxName "POI06") (CallFunction|VisitTourPlace :Index 6))
(if (== BoxName "POI07") (CallFunction|VisitTourPlace :Index 7))
(if (== BoxName "POI08") (CallFunction|VisitTourPlace :Index 8))
(if (== BoxName "POI09") (CallFunction|VisitTourPlace :Index 9))
(if (== BoxName "POI10") (CallFunction|VisitTourPlace :Index 10))
(if (== BoxName "POI11") (CallFunction|VisitTourPlace :Index 11))
(if (== BoxName "POI12") (CallFunction|VisitTourPlace :Index 12))
(if (== BoxName "POI13") (CallFunction|VisitTourPlace :Index 13))
(if (== BoxName "POI14") (CallFunction|VisitTourPlace :Index 14))
(if (== BoxName "POI15") (CallFunction|VisitTourPlace :Index 15))
(if (== BoxName "POI16") (CallFunction|VisitTourPlace :Index 16))
(if (== BoxName "POI17") (CallFunction|VisitTourPlace :Index 17))
(if (== BoxName "POI18") (CallFunction|VisitTourPlace :Index 18))
(if (== BoxName "POI19") (CallFunction|VisitTourPlace :Index 19))
(if (== BoxName "POI20") (CallFunction|VisitTourPlace :Index 20))
(if (== BoxName "POI21") (CallFunction|VisitTourPlace :Index 21))
(if (== BoxName "POI22") (CallFunction|VisitTourPlace :Index 22))
(if (== BoxName "POI23") (CallFunction|VisitTourPlace :Index 23))
(if (== BoxName "Continue") (CallFunction|SetTourMenu :Open false))
(if (== BoxName "Help") (Variables|Default|SetHelpOpen (not (Variables|Default|GetHelpOpen))))
(if (== BoxName "Volume") (CallFunction|CycleTourVolume))
(if (== BoxName "Quality1") (CallFunction|SelectTourQuality :Quality 1))
(if (== BoxName "Quality2") (CallFunction|SelectTourQuality :Quality 2))
(if (== BoxName "Quality3") (CallFunction|SelectTourQuality :Quality 3))
(if (== BoxName "Exit") (bind explorer (Utilities|Casting|CastToBP_WZMS_Explorer :Object (Game|GetPlayerPawn 0))
 (:then (Class|BPWZMSExplorer|SaveTourProgress :self explorer) (Game|QuitGame :SpecificPlayer (Game|GetPlayerController 0) :QuitPreference "Quit")) (:CastFailed))))
(event EventHitBoxBeginCursorOver (BoxName) (Variables|Default|SetHoverName BoxName))
(event EventHitBoxEndCursorOver (BoxName) (Variables|Default|SetHoverName "None"))